env:
  # TERM variable
  #
  # This value is used to set the `$TERM` environment variable for
  # each instance of Alacritty. If it is not present, alacritty will
  # check the local terminfo database and use `alacritty` if it is
  # available, otherwise `xterm-256color` is used.
  TERM: xterm-256color
  # TERM: alacritty
font:
  size: 14
  # Normal (roman) font face
  normal:
    # Font family
    #
    # Default:
    #   - (macOS) Menlo
    #   - (Linux/BSD) monospace
    #   - (Windows) Consolas
    family: Hack Nerd Font Mono

key_bindings:
#   - { key: u,         mods: Control,                    action: ClearLogNotice }
  - { key: Left,        mods: Alt,     chars: "\x1bb"                       }
  - { key: Right,       mods: Alt,     chars: "\x1bf"                       }

live_config_reload: true
