wtf:
  colors:
    border:
      focusable: darkslateblue
      focused: orange
      normal: gray
  # grid:
  #   columns: [55, 55]
  #   rows: [5,7,10,15,15]
  refreshInterval: 1
  mods:
    clocks_a:
      colors:
        rows:
          even: "lightblue"
          odd: "white"
      enabled: true
      locations:
        Ho Chi Minh: "Asia/Ho_Chi_Minh"
        Brisbane: "Australia/Brisbane"
        Perth: "Australia/Perth"
        Berlin: "Europe/Berlin"
      position:
        top: 0
        left: 0
        height: 1
        width: 1
      refreshInterval: 15
      sort: "alphabetical"
      title: "🕚"
      type: "clocks"
    prettyweather:
      title: "🌥"
      enabled: true
      city: "ho chi minh"
      position:
        top: 0
        left: 1
        height: 1
        width: 1
      refreshInterval: 5m
      unit: "m"
      view: 0
      language: "en"
    ipinfo:
      colors:
        name: "lightblue"
        value: "white"
      enabled: true
      position:
        top: 1
        left: 0
        height: 1
        width: 1
      refreshInterval: 150
    power:
      enabled: true
      position:
        top: 1
        left: 1
        height: 1
        width: 1
      refreshInterval: 15
      title: "⚡️"
    # spotify:
    #   enabled: true
    #   colors:
    #     label: "green"
    #     text: "white"
    #   position:
    #     top: 1
    #     left: 0
    #     height: 1
    #     width: 1
    #   refreshInterval: 0
    jira:
      position:
        top: 2
        left: 0
        height: 1
        width: 2
      apiKey: "${JIRA_API_KEY}"
      colors:
        rows:
          even: "lightblue"
          odd: "white"
      domain: "https://go1web.atlassian.net"
      email: "phuc.nguyen@go1.com"
      enabled: true
      jql: "issueType in (Story, Task, Sub-task, Bug, Defect) AND status not in (Done, Rejected)"
      project: "DO"
      refreshInterval: 15m
      username: "Nikk Nguyen"
      verifyServerCertificate: true
    cmdrunner:
      position:
        top: 3
        left: 0
        height: 1
        width: 2
      args: ["modified.after:yesterday", "all"]
      cmd: "task"
      enabled: true
      refreshInterval: 10m
    # gitlabtodo:
    #   position:
    #     top: 4
    #     left: 0
    #     height: 1
    #     width: 2
    #   apiKey: ""
    #   domain: "https://code.go1.com.au"
    #   enabled: true
    #   numberOfTodos: 12,
    #   refreshInterval: 5m
    #   showProject: true
